//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMessage
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int TCharacterID { get; set; }
        public int FromID { get; set; }
        public int Status { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public byte[] Items { get; set; }
        public byte[] Equips { get; set; }
        public int Gold { get; set; }
        public int Exp { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual TCharacter Character { get; set; }
    }
}
